import { Annotation } from "@langchain/langgraph";
import type { WorkflowStateName } from "../state/index.js";

export const WorkflowAnnotation = Annotation.Root({
  repoRoot: Annotation<string>,
  productRoot: Annotation<string>,
  sourceRepoRoot: Annotation<string>,
  productId: Annotation<string>,
  traceId: Annotation<string>,
  stateFile: Annotation<string>,
  transitionLogFile: Annotation<string>,
  policyFile: Annotation<string | undefined>,
  issueReportFile: Annotation<string | undefined>,
  executionDir: Annotation<string>,
  verificationMode: Annotation<"pass" | "fail">,
  handoffRef: Annotation<string>,
  requirementsRef: Annotation<string>,
  technologyRef: Annotation<string>,
  developmentPlanRef: Annotation<string>,
  executionPlanRef: Annotation<string>,
  approvalsRef: Annotation<string>,
  approvalLogFile: Annotation<string>,
  requirementsFile: Annotation<string>,
  technologyFile: Annotation<string>,
  developmentPlanFile: Annotation<string>,
  executionPlanFile: Annotation<string>,
  livingDocReportFile: Annotation<string>,
  livingDocReportRef: Annotation<string>,
  policySchemaReportFile: Annotation<string>,
  policySchemaReportRef: Annotation<string>,
  branchSpecRef: Annotation<string>,
  cwoRef: Annotation<string>,
  failureMemoryFile: Annotation<string>,
  forcedContextFile: Annotation<string>,
  loopGuardFile: Annotation<string>,
  failureScope: Annotation<string>,
  failureTestId: Annotation<string>,
  failureErrorSignature: Annotation<string>,
  retryCount: Annotation<number>,
  retryBudget: Annotation<number>,
  proposedFix: Annotation<string>,
  currentState: Annotation<WorkflowStateName | null>,
  approvalDecision: Annotation<"APPROVE" | "REJECT" | null>,
  transitionHistory: Annotation<string[]>({
    reducer: (left, right) => left.concat(right),
    default: () => [],
  }),
  artifactHistory: Annotation<string[]>({
    reducer: (left, right) => left.concat(right),
    default: () => [],
  }),
  issueReportRefs: Annotation<string[]>({
    reducer: (left, right) => left.concat(right),
    default: () => [],
  }),
});
